name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    runs-on: [ self-hosted, linux, x64 ]
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Determine if prerelease
      id: prerelease
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        VERSION="${TAG#v}"
        PATCH="${VERSION##*.}"

        if [ "$PATCH" != "0" ]; then
          echo "is_prerelease=true" >> $GITHUB_OUTPUT
        else
          echo "is_prerelease=false" >> $GITHUB_OUTPUT
        fi

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: ${{ steps.prerelease.outputs.is_prerelease }}
