services:
  origin:
    image: timefactory/origin
    container_name: origin
    restart: always
    pull_policy: always
    networks:
      - timefactory
    environment:
      - ORIGIN=timefactory.io
      - CIRCUIT=origin.timefactory.io
      - TITLE=the perpetual motion machine
      - LOGO=https://zero.s3.timefactory.io/timefactory.svg
      - TEXT=https://raw.githubusercontent.com/timefactoryio/pathless/refs/heads/main/mechanics.md
      - SLIDES=https://zero.s3.timefactory.io/slides
    labels:
      - traefik.enable=true
      - traefik.http.routers.origin.service=origin
      - traefik.http.routers.origin.rule=Host(`timefactory.io`)
      - traefik.http.routers.origin.entrypoints=websecure
      - traefik.http.routers.origin.tls=true
      - traefik.http.routers.origin.tls.certresolver=cloudflare
      - traefik.http.services.origin.loadbalancer.server.port=1000

      - traefik.http.routers.circuit.rule=Host(`origin.timefactory.io`)
      - traefik.http.routers.circuit.entrypoints=websecure
      - traefik.http.routers.circuit.tls=true
      - traefik.http.routers.circuit.tls.certresolver=cloudflare
      - traefik.http.routers.circuit.service=circuit
      - traefik.http.services.circuit.loadbalancer.server.port=1001

networks:
  timefactory:
    external: true
