services:
  sourcify:
    image: ghcr.io/argotorg/sourcify/server
    container_name: sourcify
    ports:
      - 127.0.0.1:5555:5555
    # expose:
    #   - "5555"
    environment:
      - SOURCIFY_POSTGRES_HOST=postgres
      - SOURCIFY_POSTGRES_DB=sourcify
      - SOURCIFY_POSTGRES_USER=postgres
      - SOURCIFY_POSTGRES_PORT=5432
      - SOURCIFY_POSTGRES_PASSWORD=${PASSWORD}
      - NODE_ENV=production
    volumes:
      - ./default.js:/home/app/services/server/dist/config/default.js
      - ./sourcify-chains.json:/home/app/services/server/dist/sourcify-chains.json
    networks:
      - timefactory
    restart: unless-stopped

  fourbyte:
    image: ghcr.io/argotorg/sourcify/4byte
    container_name: fourbyte
    ports:
      - 127.0.0.1:5556:80
    environment:
      - FOURBYTES_POSTGRES_HOST=postgres
      - FOURBYTES_POSTGRES_DB=sourcify
      - FOURBYTES_POSTGRES_USER=postgres
      - FOURBYTES_POSTGRES_PASSWORD=${PASSWORD}
      - FOURBYTES_POSTGRES_PORT=5432
      - NODE_ENV=production
    networks:
      - timefactory
    restart: unless-stopped

networks:
  timefactory:
    external: true
