services:
  block:
    container_name: block
    image: timefactory/block:dev
    pull_policy: always
    volumes:
      - geth:/.ethereum
      - ./output:/output
    networks:
      - timefactory
    environment:
      - PASSWORD=${PASSWORD}

networks:
  timefactory:
    external: true
volumes:
  geth:
    external: true
